---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI-NB.
--- DateTime: 2022/6/4 21:20
---
---
local eventDispatcher = cc.Director:getInstance():getEventDispatcher()

local NewGame = class("NewGame", function()
    return display.newScene("NewGame")
end)
function NewGame:ctor()

    self:iniInterface()
end
function NewGame:iniInterface()

    --背景图片
    local sp = display.newSprite("res/ui/main/bg_menu.jpg")
    sp:pos(display.cx, display.cy)
    sp:addTo(self)
    sp:setScale(1.3)

    print(cc.UserDefault:getInstance():getStringForKey("id"))
    if cc.UserDefault:getInstance():getStringForKey("id")=="nil" then
        local AnotherScene=require("app/scenes/zhuCe"):new()
        display.replaceScene(AnotherScene, "fade", 0.5)
    else
        local AnotherScene1=require("app/scenes/game"):new()
        display.replaceScene(AnotherScene1, "fade", 0.5)

    end
end
return NewGame
