---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI-NB.
--- DateTime: 2022/6/4 21:21
---
local eventDispatcher = cc.Director:getInstance():getEventDispatcher()

local Rank = class("Rank", function()
    return display.newScene("Rank")
end)
function Rank:ctor()
    self:iniInterface()

    local listView = ccui.ListView:create()
    listView:setContentSize(400, 300)
    listView:setAnchorPoint(0.5, 0.5)
    listView:setPosition(display.cx, display.top-380)
    listView:setDirection(1)
    listView:addTo(self)
    local score={"10000","9000","8000","7000","6000"}
    if(score[1]<cc.UserDefault:getInstance():getStringForKey("score") )  then
        score[1]=cc.UserDefault:getInstance():getStringForKey("score")
    end
    for i = 1, 5 do
        local img = ccui.ImageView:create("res/ui/rank/rank_item_bg.png")
        img:setScale9Enabled(true)  --开启九宫格
        img:setContentSize(cc.size(400,70))
        listView:pushBackCustomItem(img)

        local img1 = ccui.ImageView:create("res/ui/rank/rank_bg.png")
        img1:setAnchorPoint(0.5,0.5)
        img1:setScale9Enabled(true)  --开启九宫格
        img1:setContentSize(cc.size(280,50))
        img1:pos(230,35)
        img1:addTo(img)

        local font1 = ccui.Text:create("昵称" .. i, "res/ui/font/FontNormal.ttf", 35)
        font1:addTo(img)
        font1:setAnchorPoint(0.5, 0.5)
        font1:pos(150, 40)

        local font2 = ccui.TextBMFont:create(score[i], "res/ui/rank/islandcvbignum.fnt")
        font2:setScale(0.3)
        font2:setAnchorPoint(1.0,0.5)
        font2:pos(350,35)
        font2:addTo(img)

        if i<=3  then
            local font = ccui.TextBMFont:create(i, "res/ui/rank/islandcvbignum.fnt")
            font:setScale(0.5)
            font:setAnchorPoint(0.5,0.5)
            font:pos(35,35)
            font:addTo(img)


        elseif i>3 then
            local font = ccui.Text:create(i, "res/ui/font/FontNormal.ttf", 35)
            font:setScale(1.5)
            font:setAnchorPoint(0.5,0.5)
            font:pos(35,35)
            font:addTo(img)
        end

    end
end
function Rank:iniInterface()
    local sp = display.newSprite("res/ui/main/bg_menu.jpg")
    sp:pos(display.cx, display.cy)
    sp:addTo(self)
    sp:setScale(1.3)

    display.newTTFLabel({
        text = "排行榜:",
        size = 25,
        color = display.COLOR_WHITE
    }):align(display.LEFT_CENTER, 70, display.top - 130):addTo(self)

    -- back button
    local btn = ccui.Button:create("res/ui/back_peek0.png","res/ui/back_peek1.png",1)
    btn:pos(100, display.top-50)
    btn:addTo(self)
    btn:addTouchEventListener(function(sender, eventType)
        if 2 == eventType then
            local AnotherScene=require("app.scenes.MainScene"):new()
            display.replaceScene(AnotherScene,"fade",0.5)
        end
    end)
end
return Rank