---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI-NB.
--- DateTime: 2022/6/4 21:21
---
local eventDispatcher = cc.Director:getInstance():getEventDispatcher()

local Setting = class("Setting", function()
    return display.newScene("Setting")
end)

function Setting:ctor()
    self:iniInterface()
end
function Setting:cs()
    print("12sfqwer")
end
function Setting:iniInterface()
    local sp = display.newSprite("res/ui/main/bg_menu.jpg")
    sp:pos(display.cx, display.cy)
    sp:addTo(self)
    sp:setScale(1.3)
    -- back button
    local btn = ccui.Button:create("res/ui/back_peek0.png","res/ui/back_peek1.png",1)
    btn:pos(100, display.top-50)
    btn:addTo(self)
    btn:addTouchEventListener(function(sender, eventType)
        if 2 == eventType then
            local AnotherScene=require("app/scenes/MainScene"):new()
            display.replaceScene(AnotherScene,"fade",0.5)
        end
    end)


    --音效控制
    local sprite = display.newSprite("res/ui/setting/sound_click_contrl_cover.png")
    sprite:pos(display.cx, display.cy + 200)
    sprite:addTo(self)

    local landscapeCheckBox = ccui.CheckBox:create("res/ui/setting/soundon2_cover.png",
            nil,
            "res/ui/setting/soundon1_cover.png",
            nil,
            nil)
            :align(display.LEFT_CENTER, display.cx-140, display.cy+130)
            :addTo(self)



    landscapeCheckBox:addEventListener(function(sender, eventType)
        -- body
        if 1==eventType then
            audio.stopBGM("res/sounds/bgMusic.ogg")
            cc.UserDefault:getInstance():setBoolForKey("yinyue",false)
        else
            audio.playBGM("res/sounds/bgMusic.ogg",true)
            cc.UserDefault:getInstance():setBoolForKey("yinyue",true)
        end
    end)

    --音乐控制
    local sprite1 = display.newSprite("res/ui/setting/bg_music_contrl_cover.png")
    sprite1:pos(display.cx, display.cy + 50)
    sprite1:addTo(self)

    local landscapeCheckBox1 = ccui.CheckBox:create("res/ui/setting/soundon2_cover.png",
            nil,
            "res/ui/setting/soundon1_cover.png",
            nil,
            nil)
            :align(display.LEFT_CENTER, display.cx-140, display.cy-20)
            :addTo(self)

    landscapeCheckBox1:addEventListener(function(sender, eventType)
        -- body
        if 1==eventType then
            cc.UserDefault:getInstance():setBoolForKey("yinxiao",false)
        else
            cc.UserDefault:getInstance():setBoolForKey("yinxiao",true)
        end
    end)



    display.newTTFLabel({
        text = "版本号:v0.0",
        size = 25,
        color = cc.c4b(255,0,0,0.5)
    })
           :align(display.LEFT_CENTER, display.cx-140, display.cy-130)
           :addTo(self)

    display.newTTFLabel({
        text = "联系方式:13942502067",
        size = 25,
        color = cc.c3b(155,155,155)
    })
           :align(display.LEFT_CENTER, display.cx-140, display.cy-170)
           :addTo(self)

    display.newTTFLabel({
        text = "_____________________",
        size = 25,
        color = display.COLOR_WHITE
    })
           :align(display.LEFT_CENTER, display.cx-140, display.cy-170)
           :addTo(self)
end
return Setting