---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI-NB.
--- DateTime: 2022/6/5 15:04
---
local eventDispatcher = cc.Director:getInstance():getEventDispatcher()

local zhuCE = class("zhuCE", function()
    return display.newScene("zhuCE")
end)


function zhuCE:ctor()
    self:iniInterface()

end
function zhuCE:iniInterface()

    local sp = display.newSprite("res/ui/main/bg_menu.jpg")
    sp:pos(display.cx, display.cy)
    sp:addTo(self)
    sp:setScale(1.3)

    display.newTTFLabel({
        text = "您是新用户，请您先注册:",
        size = 25,
        color = display.COLOR_WHITE
    })
           :align(display.LEFT_CENTER, 70, display.top - 180)
           :addTo(self)

    local locationEditbox = ccui.EditBox:create(cc.size(display.width-150, 40), COLOR_WHITE, 1)
    locationEditbox:setAnchorPoint(0,0)
    locationEditbox:pos(70, display.top - 270)
    locationEditbox:addTo(self)


    local function getUUID()
        local curTime = os.time()
        local uuid = curTime + math.random(10000000)
        return uuid
    end

    local zhuceButton = ccui.Button:create("res/ui/register/register.png", 1)
    zhuceButton:setScale9Enabled(true)
    zhuceButton:setContentSize(cc.size(150, 50))
    zhuceButton:addTouchEventListener(function(sender, eventType)
        if 2 == eventType then
            if locationEditbox:getText()==""then
                cc.UserDefault:getInstance():setStringForKey("id","a")
            else
                cc.UserDefault:getInstance():setStringForKey("name",locationEditbox:getText())
                cc.UserDefault:getInstance():setStringForKey("id",getUUID())
                self:removeFromParent(true)
                local AnotherScene1=require("app/scenes/game"):new()
                display.replaceScene(AnotherScene1, "fade", 0.5)
            end
        end
    end)
        zhuceButton:pos(display.cx,display.cy+150)
        zhuceButton:addTo(self)

    function zhuCE:onEnter()
    end

    function zhuCE:onExit()
    end
end

return zhuCE