---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2022/6/10 1:29
---

require "app/Common"


local function makeKey(x,y)
    return x*1000+y
end

--10*20 游戏区域格子


local Scene = class("Scene")

function Scene:ctor(node)
    self.map = {}
    for  x=0,cSceneWidth-1 do
        for  y=0, cSceneHeight-1 do
            local xx,yy =Grid2Pos(x,y)
            local sp = display.newSprite("res/texture/t_1.png")
            sp:setScale(0.33)
            sp:pos(xx,yy)
            sp:addTo(node)
            local visible  =  (x==0 or x==cSceneWidth-1 ) or y==0

            sp:setVisible(visible)
            self.map[makeKey(x,y)]=sp
        end
    end
end

function Scene:ClearLine(y)
    for x =1 ,cSceneWidth-2 do
        self:Set(x,y,false)
    end
end

function Scene:Clear()
    for y=1,cSceneHeight-1 do
        self:ClearLine(y)
    end
end
function Scene:Set(x,y,value)
    local sp =self.map[makeKey(x,y)]
        if  sp==nil then
            return
        end
    sp:setVisible(value)
end

function Scene:Get(x,y)
    local sp=self.map[makeKey(x,y)]
        if  sp==nil then
            return
        end
    return  sp:isVisible()
end


return Scene