---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2022/7/8 20:47
---

local IngameMsg = class("IngameMsg", function()
    return display.newScene("IngameMsg")
end)

local MsgController = require("app.msg.MsgController")
local Log = require("app.util.Log")
local TAG = "MainScene"
local delay=999 --延迟，单位ms 默认未连接状态为999ms


function IngameMsg:handleMsg(msg)

    Log.i(TAG, "handleMsg() msg=", msg)
end


function IngameMsg:handle(aloginname,data)

    local handlemsg= {
        type = 2,
        loginName = aloginname,
        data = data,
    }
    MsgController:sendMsg(handlemsg)
end

function IngameMsg:Giveup(aloginname)
     local Giveupmsg ={
         type=3,
         loginName =aloginname,
     }
    MsgController:sendMsg(Giveupmsg)
end



function IngameMsg:onEnter()
    MsgController:registerListener(self, handler(self, self.handleMsg))
end

function IngameMsg:onExit()
    MsgController:unregisterListener(self)
end

function IngameMsg:handleMsg(msg)
    print("OutgameMsg")
    print(msg.financeData.gold)
end

return IngameMsg