---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2022/7/14 15:40
---

----本文件只作为一个说明，不参与运行

----数据类型分别为
---financeData
---towerData
---achieveData
---lineupData
---otherData   五部分，将在与客户端的数据传输中被使用，数据类型名需被当做dataType参数
Player = {
    pid = 0,
    loginName = "",
    passWord = "",
    nick="",


    financeData={
        gold=0, --金币数
        diamond=0, --钻石数
        trophyAmount=0,  --奖杯总数
    },
    towerData={
        id={},--塔的id
        num={},--塔的数量
        level={},--塔的等级
        --tower={},--tower[塔的种类]={塔的数量，塔的等级}
    },
    achieveData={
        --trophyAmount=0,  --奖杯总数
        rankObjectAmount={},--22个天梯物品获取状态信息（1未达到奖杯数要求，2达到奖杯数要求并未开启过，3开启过）
        --rankObject={},--rankObject[天梯物品的种类]={状态信息}

    },
    lineupData={
        lineup={},--这是当前选择的阵容，就用1，2，3分别表示,lineup[编号]={塔的种类【1~5,6~10,11~15分别为三个阵容，】}
        level={},--塔的等级
    },
    otherData={
        headPortrait="", --头像框
    },

    sid = 0,
}

