---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/8 14:20
---
display.addSpriteFrames("res/animation/explosion.plist", "res/animation/explosion.png")

local Boom = class("Boom")
Boom.sprite = nil
Boom.animate = nil
function Boom:ctor()

end
function Boom:init(x, y)
    local frames = display.newFrames("explosion_%02d.png", 1, 35)
    local animation = display.newAnimation(frames, 1 / 35)
    local animate = cc.Animate:create(animation)
    self.animate = animate

    self.sprite = display.newSprite("#explosion_01.png")
    self.sprite:performWithDelay(function()
        self.sprite:removeSelf()
    end, 1)
    self.sprite:setPosition(x, y)
end
function Boom:getAnimate()
    return self.animate
end
function Boom:play()
    self.sprite:runAction(self.animate)
end
return Boom