---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/8 14:20
---
local Bullet = class("Bullet", function()
    return cc.Sprite:create("res/player/blue_bullet.png")
end)

Bullet.bx = -100
Bullet.by = -100
Bullet.speed = 15
Bullet.alive = false
function Bullet:ctor()

end
function Bullet:init(x, y)
    self.bx = x
    self.by = y
    self.alive = true
    self:setPosition(self.bx, self.by)
end
function Bullet:move()
    --print(self.x , self.y)
    self.by = self.by + self.speed
    self:setPosition(self.bx, self.by)
end
function Bullet:setAlive(alive)
    self:setVisible(alive)
    self.alive = alive
end
function Bullet:isAlive()
    return self.alive
end
function Bullet:getBulletPosition()
    return self.bx, self.by
end
return Bullet