---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/9 11:13
---
local EnemyList = class("Enemy")

EnemyList.data = {}
EnemyList.num = 0
EnemyList.head = 1
EnemyList.tail = 1
EnemyList.size = 10
math.randomseed(tostring(os.time()):sub(1,6))
function EnemyList:ctor()

end
function EnemyList:add(x, y)
    local Enemy = require("src/app/models/pojo/Enemy.lua")
    local enemy = Enemy:new()
    enemy:init(x, y)
    self.data[self.head] = enemy
    self.head = self.head + 1
    self.num = self.num + 1
    if self.num > self.size then
        return self:remove(), enemy
    else
        return nil, enemy
    end
end
function EnemyList:remove()
    local value = self.data[self.tail]
    self.data[self.tail] = nil
    self.tail  = self.tail + 1
    self.num = self.num - 1
    return value
end
function EnemyList:iterator()
    local counter = self.tail - 1
    return function()
        counter = counter + 1
        if counter < self.head then
            return self.data[counter]
        else
            return nil
        end
    end
end

function EnemyList:getRandomX()
    return math.random(20, display.width - 20)
end

return EnemyList