---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/8 23:58
---
local Enemy = class("Enemy", function()
    return cc.Sprite:create("res/player/small_enemy.png")
end)
Enemy.ex = -100
Enemy.ey = -100
Enemy.speed = 5
Enemy.alive = false
function Enemy:ctor()

end
function Enemy:init(x, y)
    --print(x, y)
    self.alive = true
    self.ex = x
    self.ey = y
    self:setPosition(self.ex, self.ey)
end
function Enemy:move()
    --print(self.x , self.y)
    --print(self.x, self.y)
    self.ey = self.ey - self.speed
    self:setPosition(self.ex, self.ey)
end
function Enemy:getEnemyPosition()
    --print(self.x, self.y)
    return self.ex, self.ey
end
function Enemy:setAlive(alive)
    self.alive = alive
    self:setVisible(alive)
end
function Enemy:isAlive()
    return self.alive
end

return Enemy