---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/9 21:32

local spineSP = class("spineSP", function()
    return sp.SkeletonAnimation:createWithJsonFile(
            "res/spine/fireBoom/7_1_fireBoom.json", "res/spine/fireBoom/7_1_fireBoom.atlas"
    )
end)
function spineSP:ctor()

end
function spineSP:init(x, y)
    self:setPosition(x, y)

    --self:registerSpineEventHandler(function()  end, ANIMATION_END)
end

function spineSP:play()
    --self:setAnimation(0, "run", false)
end
return spineSP