---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/6 15:13
---
local GameConfig = class("GameConfig")
GameConfig.backgroundMusic = false
GameConfig.soundEffect = false

function GameConfig:ctor(backgroundMusic, soundEffect)
    self.soundEffect = soundEffect
    self.backgroundMusic = backgroundMusic
end
function GameConfig:setBackgroundMusic(backgroundMusic)
    self.backgroundMusic = backgroundMusic
end
function GameConfig:getBackgroundMusic()
    return self.backgroundMusic
end
function GameConfig:setSoundEffect(soundEffect)
    self.soundEffect = soundEffect
end
function GameConfig:getSoundEffect()
    return self.soundEffect
end

return GameConfig