---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/8 14:20
---
local Plain = class("Plain", function()
    return cc.Sprite:create("res/player/purple_plane.png")
end)
Plain.x = display.width * .5
Plain.y = 100
Plain.speed = 10
Plain.des = display.width * .5
--Plain.count = 1
function Plain:ctor()
    local width = self:getContentSize().width
    local sprite = display.newSprite("res/particle/fire.png")
    sprite:setPosition(width * .5, 0)
    sprite:setName("sprite")
    sprite:setScale(0.5)
    self:addChild(sprite)

    --local spineSP = sp.SkeletonAnimation:createWithJsonFile(
    --        "res/spine/fireBoom/7_1_fireBoom.json", "res/spine/fireBoom/7_1_fireBoom.atlas"
    --)
    --spineSP:setScale(0.5)
    ----spineSP:pos(display.cx, 100):addTo(self)
    --spineSP:setPosition(width * .5 - 3, 0)
    --spineSP:setAnimation(0, "run", true)
    ---- aim mode
    --spineSP:setAnimation(1, "aim", false)
    --spineSP:addTo(self)
end

function Plain:setDes(des)
    if des > display.width - 10 then
        des = display.width - 10
    elseif des < 10 then
        des = 10
    else
        self.des = des
    end
end
function Plain:move()
    if self.des > self.x + self.speed then
        self.x = self.x + self.speed
    elseif self.des < self.x - self.speed then
        self.x = self.x - self.speed
    else
        self.x = self.des
    end
    --self.count = (self.count + 1) % 12
    --local sprite = self:getChildByName("sprite")
    --if self.count < 3 then
    --    sprite:setVisible(true)
    --else
    --    sprite:setVisible(false)
    --end
    self:statusUpdate()
end
function Plain:statusUpdate()
    self:setPosition(self.x, self.y)
end
function Plain:getLocation()
    return self.x, self.y
end
return Plain