---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoybzo.
--- DateTime: 2022-05-26 11:33
---
local BaseController = class("BaseController")

function BaseController:ctor(name)
    self.name = name
    Log.i(name .. "Controller ctor")
end

return BaseController