---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI-NB.
--- DateTime: 2022/6/4 21:21
---

local eventDispatcher = cc.Director:getInstance():getEventDispatcher()

local Coutinue = class("Coutinue", function()
    return display.newScene("Coutinue")
end)
return Coutinue