---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/6 15:12
---
local BaseGameScene = require("src.app.scenes.BaseGameScene")
local ContinueGameScene = class("ContinueView", BaseGameScene)

---properties
ContinueGameScene.userPlayData = {}

function ContinueGameScene:ctor()
    self.super.ctor(self)
    --[[
    this block to use load old data
    --]]
end

return ContinueGameScene