---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by MSI-NB.
--- DateTime: 2022/6/5 15:43
---
local eventDispatcher = cc.Director:getInstance():getEventDispatcher()
local game = class("game", function()
    return display.newScene("game")
end)


function game:ctor()

    local life=100
    local score=0

    local sp = display.newSprite("res/img_bg/img_bg_1.jpg")
    sp:pos(display.cx, display.cy)
    sp:addTo(self)
    sp:setScale(1.3)

    local spFile = display.newSprite("res/ui/battle/ui_life.png")
    spFile:pos(display.cx-50,display.top-50)
    spFile:addTo(self)
    spFile:setScale(1.3)
    local font1 = ccui.TextBMFont:create(life, "res/ui/battle/num_account.fnt")
    font1:pos(display.cx+30,display.top-50)
    font1:addTo(self)

    local spScore = display.newSprite("res/ui/battle/ui_score.png")
    spScore:pos(display.cx+148,display.top-50)
    spScore:addTo(self)
    spScore:setScale(1.3)
    local font2 = ccui.TextBMFont:create(score, "res/ui/battle/num_account.fnt")
    font2:pos(display.cx+208,display.top-50)
    font2:addTo(self)

    local pauseButton = ccui.Button:create("res/ui/battle/uiPause.png", 1)
    pauseButton:addTouchEventListener(function(sender, eventType)
        if 2 == eventType then
            display.pause()
            local startLayer = ccui.Layout:create()
            startLayer:setBackGroundColorType(1)
            startLayer:setContentSize(cc.size(width,height))
            startLayer:setPosition(display.cx, display.cy)
            startLayer:setAnchorPoint(cc.p(0.5, 0.5))
            startLayer:setOpacity(127)
            startLayer:addTo(self)
            self:pauseUI()
        end
    end)
    pauseButton:setAnchorPoint(1,1)
    pauseButton:setScale(2)
    pauseButton:pos(display.cx-200, display.top )
    pauseButton:addTo(self)

end


function game:pauseUI()


end
return game