---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/6 15:12
---
local BaseGameScene = require("src.app.scenes.BaseGameScene")
local NewGameScene = class("NewGameView", BaseGameScene)

function NewGameScene:ctor()
    self.super.ctor(self)
    ---nothing to do
end

return NewGameScene