---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/7 18:10
---
local PauseView = class("PauseView", function()
    return ccui.Layout:create()
end)
---properties
PauseView.background = {
    "res/img_bg/img_bg_1.jpg"
}
PauseView.buttonDate = {
    resume = "res/ui/continue/pauseResume.png",
    backRoom = "res/ui/continue/pauseBackRoom.png"
}
PauseView.sound = {
    menuMusic = "res/sounds/mainMainMusic.ogg",
    buttonEffect = "res/sounds/buttonEffet.ogg"
}

---method
function PauseView:ctor()
    --self:createBackground()
    self:createButton()
end
--function PauseView:createBackground()
--
--    local sprite = display.newScale9Sprite(self.background[1],0,0,cc.size(width, height))
--    sprite:setAnchorPoint(0, 0)
--    sprite:setPosition(0, 0)
--    self:addChild(sprite)
--end
function PauseView:createButton()

    local width, height = display.width, display.height

    local layer = ccui.Layout:create()
    layer:setBackGroundColor(cc.c4b(96,96, 96, 100))
    layer:setBackGroundColorType(1)
    layer:setBackGroundColorOpacity(100)
    layer:setContentSize(width, height)
    layer:setPosition(0, 0)
    self:addChild(layer)

    local buttonResume = ccui.Button:create(self.buttonDate.resume, self.buttonDate.resume)
    buttonResume:setContentSize(130, 40)
    buttonResume:setPosition(width * .4, height - 400)
    buttonResume:addTouchEventListener(function(sender, eventType)

        audio.playEffectSync(self.sound.buttonEffect)

        local pauseButton = self:getParent():getChildByName("inforLayer"):getChildByName("pauseButton")

        if pauseButton then
            pauseButton:setVisible(true)
        end
        self:removeSelf()
        cc.Director:getInstance():resume()
    end)
    layer:addChild(buttonResume)

    local buttonBackRoom = ccui.Button:create(self.buttonDate.backRoom, self.buttonDate.backRoom)
    buttonBackRoom:setContentSize(130, 40)
    buttonBackRoom:setPosition(width * .4, height - 600)
    buttonBackRoom:addTouchEventListener(function(sender, eventType)
        audio.playEffectSync(self.sound.buttonEffect)
        audio.playBGMSync(self.sound.menuMusic)
        self:getParent():removeAllChildren()
        local MenuScene = require("src.app.scenes.MainScene")
        local menuScene = MenuScene:new()
        cc.Director:getInstance():replaceScene(menuScene)
    end)
    layer:addChild(buttonBackRoom)

end

return PauseView