---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/1 9:42
---
local BaseLayer = require("src.app.scenes.BaseLayer")
local RankView = class("RankView", BaseLayer)



function RankView:ctor()
    self.super.ctor(self)

    local fontData = {
        artFont = "res/ui/rank/islandcvbignum.fnt",
        FontNormal = "res/ui/font/FontNormal.ttf"
    }

    local imageData = {
        mateDataBackLocation = "res/ui/rank/rank_item_bg.png",
        backLocation = "res/ui/rank/rank_bg.png",
        numberImageLocation = "res/ui/rank/islandcvbignum.png"
    }

    local rankData = {
        {name = "昵称1", point = 10000},
        {name = "昵称2", point = 9000},
        {name = "昵称3", point = 8000},
        {name = "昵称4", point = 7000},
        {name = "昵称5", point = 6000}
    }

    self:createRankList(fontData, imageData, rankData)
end

function RankView:createRankList(fontData, imageData, rankData)
    local width, height = display.width * 0.8, display.height * 0.8
    --layer
    --local rankLayer = ccui.Layout:create()
    --rankLayer:setBackGroundColor(cc.c3b(100, 0, 0))
    --rankLayer:setBackGroundColorType(3)
    --rankLayer:setContentSize(width, height)
    --rankLayer:setPosition(10, display.top - height * 0.25)
    --rankLayer:setAnchorPoint(0, 1)
    --self:addChild(rankLayer)

    --scrollView
    local scrollView = ccui.ScrollView:create()
    scrollView:setAnchorPoint(0.5, 0.5)
    scrollView:setPosition(display.width * 0.5, display.height * 0.5)
    scrollView:setContentSize(width, height)
    scrollView:addTo(self)

    for i, v in pairs(rankData) do
        --back
        local itemWid, itemHei = width - 20, 80

        local spriteCon = display.newScale9Sprite(imageData.mateDataBackLocation, 0, 0, cc.size(itemWid ,itemHei))
        spriteCon:setAnchorPoint(0.5, 0.5)
        spriteCon:setContentSize(itemWid, itemHei)
        spriteCon:setPosition(itemWid * .5, height - 10 - i * 100)
        scrollView:addChild(spriteCon)

        local sprite = display.newScale9Sprite(imageData.backLocation, 0, 0, cc.size(itemWid - 100, itemHei - 20))
        sprite:setAnchorPoint(0.5, 0.5)
        sprite:setPosition(itemWid * 0.5 + 30, itemHei * 0.5)
        spriteCon:addChild(sprite)

        --local font = ccui.Text:create(i .. " 昵称: " .. v.name .. "  " .. v.point, fontData.FontNormal, 40)
        --font:setPosition(200, 40)
        --spriteCon:addChild(font)
        local name = ccui.Text:create(v.name, fontData.FontNormal, 50)
        name:setAnchorPoint(0, 0)
        name:setContentSize((itemWid - 100) * 0.25, itemHei - 20)
        name:setPosition(10, 0)
        sprite:addChild(name)
        if i < 4 then
            local font = ccui.TextBMFont:create(tostring(i), fontData.artFont)
            font:setScale(0.5, 0.5)
            font:setPosition(33, 40)
            spriteCon:addChild(font)

            local pointFont = ccui.TextBMFont:create(tostring(v.point), fontData.artFont)
            pointFont:setScale(0.4, 0.4)
            pointFont:setAnchorPoint(1, 0)
            pointFont:setPosition(itemWid - 110, itemHei - 70)
            sprite:addChild(pointFont)
        else
            local font = ccui.Text:create(tostring(i), fontData.FontNormal, 40)
            font:setPosition(33, 40)
            spriteCon:addChild(font)

            local pointFont = ccui.Text:create(tostring(v.point), fontData.FontNormal, 35)
            pointFont:setAnchorPoint(1, 0)
            pointFont:setPosition(itemWid - 110, itemHei - 70)
            sprite:addChild(pointFont)
        end


    end


end

return RankView