---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/5/31 14:51
---
local BaseLayer = require("src.app.scenes.BaseLayer")
local SettingView = class("SettingView", BaseLayer)
SettingView.userConfig = {}
function SettingView:ctor()
    self.super.ctor(self)
    --[[
    this block use to get user config
    not completed
    --]]
    --data
    local settingData = {
        {"backgroundMusic",
         "res/ui/setting/bg_music_contrl_cover.png",
         "res/ui/setting/soundon1_cover.png",
         "res/ui/setting/soundon2_cover.png"},
        {"soundEffect",
         "res/ui/setting/sound_click_contrl_cover.png",
         "res/ui/setting/soundon1_cover.png",
         "res/ui/setting/soundon2_cover.png"}
    }
    local labelData = {
        "版本号：1.1",
        "联系方式：17823284390"
    }

    self:createSettingButton(settingData)
end

function SettingView:createSettingButton(settingData)

    for i, v in ipairs(settingData) do
        --setting option
        local sprite = display.newScale9Sprite(v[2],0,0,cc.size(140, 40))
        sprite:setAnchorPoint(1, 1)
        sprite:pos(display.width * 0.4, display.height - 210 - 80 * i)
        sprite:setContentSize(130, 40)
        self:addChild(sprite)

        --button
        local images = {
            off = v[4],
            off_pressed = v[4],
            off_disabled = v[4],
            on = v[3],
            on_pressed = v[3],
            on_disabled = v[3]
        }

        local checkBoxButton = ccui.CheckBox:create()
        checkBoxButton:loadTextures(
                images.on,
                images.off,
                images.off_pressed,
                images.on_disabled,
                images.off_disabled
        )
        checkBoxButton:setAnchorPoint(0, 1)
        checkBoxButton:pos(display.width * 0.4, display.height - 200 - i * 80)
        checkBoxButton:addTouchEventListener(function(sender, eventType)
            --- ???奇怪
            if ccui.CheckBoxEventType.selected == eventType then
                self:soundControl(v[1])
            end
        end)
        self:addChild(checkBoxButton)
        --updateCheckButtonLabel(checkBoxButton)

    end
end
function SettingView:soundControl(str)
    if str == "backgroundMusic" then
        if audio._BGMVolume > 0 then
            audio.setBGMVolume(0)
        else
            audio.setBGMVolume(1.0)
        end
    elseif str == "soundEffect" then
        if audio._effectVolume > 0 then
            audio.setEffectVolume(0)
        else
            audio.setEffectVolume(1.0)
        end
    end
end

return SettingView