---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/7 18:11
---
local SettleView = class("SettleView", function()
    return ccui.Layout:create()
end)
---properties
SettleView.score = 0
SettleView.playerName = ""
SettleView.background = {
    "res/img_bg/img_bg_1.jpg"
}
SettleView.buttonData = {
    restart = "res/ui/gameover/restart.png",
    back = "res/ui/gameover/back.png"
}
SettleView.sound = {
    menuMusic = "res/sounds/mainMainMusic.ogg",
    buttonEffect = "res/sounds/buttonEffet.ogg"
}
SettleView.font = {
    labelFont = "res/ui/font/FontNormal.ttf"
}
---method

function SettleView:ctor(name,score)
    --self:createBackground()
    self.score = score
    self.playerName = name
    self:createButton()
end

function SettleView:createButton()
    local width, height = display.width, display.height
    local layer = ccui.Layout:create()
    layer:setBackGroundColor(cc.c4b(96,96, 96, 50))
    layer:setContentSize(width, height)
    layer:setBackGroundColorType(1)
    layer:setBackGroundColorOpacity(100)
    layer:setPosition(0, 0)
    self:addChild(layer)

    local nameLabel = display.newTTFLabel({
        text = "昵称：" .. self.playerName,
        font =  self.font.labelFont,
        size = 35
    })
    nameLabel:setAnchorPoint(1, 1)
    nameLabel:setContentSize(130, 40)
    nameLabel:setPosition(width * 0.5 - 10, height - 200)
    layer:addChild(nameLabel)

    local scoreLabel = display.newTTFLabel({
        text = "得分：" .. tostring(self.score),
        font = self.font.labelFont,
        size = 35
    })
    scoreLabel:setAnchorPoint(0, 1)
    scoreLabel:setContentSize(130, 40)
    scoreLabel:setPosition(width * 0.5 + 10, height - 200)
    layer:addChild(scoreLabel)

    local buttonRestart = ccui.Button:create(self.buttonData.restart, self.buttonData.restart)
    buttonRestart:setContentSize(130, 40)
    buttonRestart:setPosition(width * .4, height - 400)
    buttonRestart:addTouchEventListener(function(sender, eventType)
        print("clicked")
        audio.playEffectSync(self.sound.buttonEffect)

        self:getParent():removeAllChildren()
        local GameScene = require("src.app.scenes.NewGameScene")
        local gameScene = GameScene:new()
        cc.Director:getInstance():replaceScene(gameScene)
    end)
    layer:addChild(buttonRestart)

    local buttonBack = ccui.Button:create(self.buttonData.back, self.buttonData.back)
    buttonBack:setContentSize(130, 40)
    buttonBack:setPosition(width * .4, height - 600)
    buttonBack:addTouchEventListener(function(sender, eventType)
        print("clicked")
        audio.playEffectSync(self.sound.buttonEffect)
        audio.playBGMSync(self.sound.menuMusic)
        self:getParent():removeAllChildren()
        local MenuScene = require("src.app.scenes.MainScene")
        local menuScene = MenuScene:new()
        cc.Director:getInstance():replaceScene(menuScene)
    end)
    layer:addChild(buttonBack)

end
return SettleView